sudo: false

language: c
compiler:
 - gcc
 - clang

script:
 - cd ${TRAVIS_BUILD_DIR}
 - cmake . && make && ./main
 - cd ${TRAVIS_BUILD_DIR}/tests
 - cmake .. && make
 - ./test_vector && ./test_string && ./test_set && ./test_tuple

